### ISSUE TITLE
Speed up after each loop

### ISSUE THREAD

**Issue by albyr** [albyr/mobile-toy#2]
Should it be only the _Knight Rider_ sequence that speeds up, or the "normal" flash pattern too, @robobadger?

**Comment by albyr** [comment]
Fixed in 09b9881.

**Comment by robobadger** [comment]
Only the Knightrider I'd say. Still haven't sat down in front of my PC to
check this out. Apologies.

**Comment by robobadger** [comment]
I like the speed up in the KR sequence. How many loops does it run through before becoming to quick to see? Might need to vary the change a little.

**Comment by albyr** [comment]
With the default `timerShort` value of 300 ms and the default `decayFactor` of 0.15 the looping drops below the persistence of vision threshold after about twenty loops.
